services:
  traefik:
    image: traefik:v2.10
    container_name: tforce-traefik-dev
    restart: always
    ports:
      - "80:80"      # Single port for all services
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"  # Enable dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"    # More verbose logging for development
      - "--api.debug=true"
      - "--ping=true"

    networks:
      - tforce-network

  db:
    image: postgres:16-alpine
    container_name: tforce-db
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Keep direct port exposure for local development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tforce-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: tforce-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOST}
      PORT: ${PORT}
      RUST_LOG: ${RUST_LOG}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    # Keep direct port exposure for development convenience
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
      - backend_target:/app/target
    command: ./docker-entrypoint.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-dev.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend-dev.entrypoints=web"
      - "traefik.http.services.backend-dev.loadbalancer.server.port=8080"
    networks:
      - tforce-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tforce-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env.docker
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      # Use the internal API URL for container-to-container communication
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_INTERNAL_API_URL:-http://localhost/api}
    # Keep direct port exposure for development convenience
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend-dev.entrypoints=web"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-dev.priority=1"
    networks:
      - tforce-network

volumes:
  postgres_data:
  backend_target:

networks:
  tforce-network:
    driver: bridge